apiVersion: v1 
kind: Pod 
metadata:
    name: nginxpod
    labels: 
        zone: prod 
        version: v1 
        app: nginx-app
        name: dns-nginx
spec: 
    hostname: nginx-01
    containers: 
      - name: nginxcontent
        image: ngixcontent
        imagePullPolicy: Never
        ports: 
          - containerPort: 80
        # Nginx container starts nginx daemon, no need to specify an entrypoint
        #command: [ "/bin/bash", "-c", "--" ]
        #args: [ "while true; do sleep 30; done;" ]
