apiVersion: v1
kind: Service
metadata: 
    name: ngix-svc1
    labels:
        app: ngix-svc
spec:
    type: NodePort
    ports:
    - port: 80
      nodePort: 30006
      protocol: TCP
    selector:
      app: ngix-app
