apiVersion: v1
kind: Service
metadata: 
    name: nginx-svc1
    labels:
        app: nginx-svc
spec:
    type: NodePort
    ports:
    - port: 80
      nodePort: 30008
      protocol: TCP
    selector:
      app: nginx-app
